"""initial attendance schema

Revision ID: 38ecc9c4d816
Revises:
Create Date: 2026-09-30 18:05:28.944653

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38ecc9c4d816"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("hired_on", sa.Date(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
    )
    op.create_table(
        "holidays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holidays")),
        sa.UniqueConstraint("day", name=op.f("uq_holidays_day")),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("username_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_login_attempts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_login_attempts_ip_address"), ["ip_address"], unique=False)
        batch_op.create_index(batch_op.f("ix_login_attempts_username_digest"), ["username_digest"], unique=False)

    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("saturday_start", sa.Time(), nullable=False),
        sa.Column("saturday_end", sa.Time(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("interval_minutes >= 0", name=op.f("ck_schedules_positive_interval")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("name", name=op.f("uq_schedules_name")),
    )
    op.create_table(
        "system_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("setup_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_state")),
    )
    op.create_table(
        "employee_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until >= valid_from", name=op.f("ck_employee_schedules_valid_dates")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["employees.id"], name=op.f("fk_employee_schedules_employee_id_employees")
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"], ["schedules.id"], name=op.f("fk_employee_schedules_schedule_id_schedules")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_schedules")),
        sa.UniqueConstraint("employee_id", "valid_from", name=op.f("uq_employee_schedules_employee_id")),
    )
    with op.batch_alter_table("employee_schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_employee_schedules_employee_id"), ["employee_id"], unique=False)

    op.create_table(
        "time_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("corrected_at", sa.DateTime(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("source IN ('SERVIDOR', 'CORRECAO')", name=op.f("ck_time_records_valid_source")),
        sa.CheckConstraint(
            "type IN ('ENTRADA', 'INTERVALO_SAIDA', 'INTERVALO_RETORNO', 'SAIDA')",
            name=op.f("ck_time_records_valid_type"),
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], name=op.f("fk_time_records_employee_id_employees")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_records")),
        sa.UniqueConstraint("employee_id", "work_date", "type", name=op.f("uq_time_records_employee_id")),
    )
    with op.batch_alter_table("time_records", schema=None) as batch_op:
        batch_op.create_index("ix_time_records_employee_date", ["employee_id", "work_date"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("role != 'FUNCIONARIO' OR employee_id IS NOT NULL", name=op.f("ck_users_employee_required")),
        sa.CheckConstraint("role IN ('FUNCIONARIO', 'DIRETORIA')", name=op.f("ck_users_valid_role")),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], name=op.f("fk_users_employee_id_employees")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("employee_id", name=op.f("uq_users_employee_id")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)

    op.create_table(
        "correction_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("time_record_id", sa.Integer(), nullable=True),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("requested_type", sa.String(length=30), nullable=False),
        sa.Column("previous_value", sa.DateTime(), nullable=True),
        sa.Column("requested_value", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "requested_type IN ('ENTRADA', 'INTERVALO_SAIDA', 'INTERVALO_RETORNO', 'SAIDA')",
            name=op.f("ck_correction_requests_valid_type"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDENTE', 'APROVADO', 'RECUSADO')", name=op.f("ck_correction_requests_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["employees.id"], name=op.f("fk_correction_requests_employee_id_employees")
        ),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], name=op.f("fk_correction_requests_reviewed_by_users")),
        sa.ForeignKeyConstraint(
            ["time_record_id"], ["time_records.id"], name=op.f("fk_correction_requests_time_record_id_time_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_correction_requests")),
    )
    with op.batch_alter_table("correction_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_correction_requests_status"), ["status"], unique=False)
        batch_op.create_index("ix_corrections_employee_date", ["employee_id", "work_date"], unique=False)

    state = sa.table("system_state", sa.column("id", sa.Integer), sa.column("setup_completed", sa.Boolean))
    op.bulk_insert(state, [{"id": 1, "setup_completed": False}])
    # ### end Alembic commands ###


def downgrade():
    # Dropping each table removes its indexes too. InnoDB may use a composite
    # index for a foreign key, so dropping the index first is not portable.
    op.drop_table("correction_requests")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("time_records")
    op.drop_table("employee_schedules")
    op.drop_table("system_state")
    op.drop_table("schedules")
    op.drop_table("login_attempts")
    op.drop_table("holidays")
    op.drop_table("employees")
